<<<<<<< HEAD
# site properties and page defaults
title: Sustainable Energy Storage & Recycling Group (SESR Group)
subtitle: Institute for Material Discovery , School of Chemistry , University College London
=======
# Site properties and page defaults
title: Sustainable Energy Storage & Recycling Group (SESR Group)
subtitle: University College London
>>>>>>> 946fbb775d4734cc55c1ca1645c2b119b1501f03
description: >
  Welcome to the Sustainable Energy Storage & Recycling Group (SESR Group), led by Dr. Nikiforidis Georgios at the University College London. Our mission is to advance the development and implementation of sustainable energy storage materials and technologies, focusing on the circular economy of electric vehicle (EV) batteries, bio-energy production, and green electrolyte engineering. We are at the forefront of research and development, pioneering solutions that bridge the gap between green energy and cutting-edge digital processes. With a shared commitment to a more sustainable future, we explore the intersection of renewable energy technologies and digital optimization methods. Our expertise and collaborative spirit drive us to create a world where clean energy and digital innovation coexist harmoniously, revolutionizing the way we power our planet. Join us on this journey towards a sustainable future and discover the innovative projects and groundbreaking research being pursued by our dedicated team.
header: images/background.jpg
footer: images/background.jpg

# Site social media and other links
links:
  email: haotianteemo@outlook.com
  orcid: 0000-0001-8713-9213
  google-scholar: https://scholar.google.com/citations?user=3D4G2t8AAAAJ&hl=en&oi=ao
  github: Sustainable-Energy-Storage-Recycling
  twitter: YourLabHandle
  youtube: https://www.youtube.com/watch?v=fkX-H24Chfw

### Jekyll settings

# Front matter defaults
defaults:
  # All markdown files
  - scope:
      path: ""
    values:
      layout: default
  # Markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # Markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# Collections
collections:
  # Generate page for each member
  members:
    output: true
  # Generate page for each post
  posts:
    output: true

# Jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# Code block syntax highlighting
highlighter: rouge

# Jekyll theme
theme: null

# SASS settings
sass:
  sass_dir: _styles

# Force Jekyll to include certain files/folders
include:
  - _styles
  - _scripts
  - assets/images/Green-Hydrogen.jpg
  - assets/images/energy-storage.png

# Force Jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
