- id: doi:10.1016/j.rser.2010.06.014
  type: paper
  description: The present review is a critical appraisal of the commercialization potential of microalgae biofuels. 
  date: 2010-12-4
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1364032110001619-gr3.jpg
  buttons:
    - type: Biofuels
      link: https://en.wikipedia.org/wiki/Biofuel
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review

  tags:
    - Commercialization
    - Biofuels
  repo: https://www.sciencedirect.com/science/article/pii/S1364032110001619

- id: doi:10.1016/j.energy.2023.127922
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0360544223013166-gr13_lrg.jpg

- id: doi:10.1016/j.fuel.2022.126368
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0016236122031921-ga1_lrg.jpg

- id: doi:10.1007/s40747-022-00724-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs40747-022-00724-7/MediaObjects/40747_2022_724_Fig1_HTML.png?as=webp

- id: doi:10.3390/jimaging8070199
  image: https://pub.mdpi-res.com/jimaging/jimaging-08-00199/article_deploy/html/images/jimaging-08-00199-g002.png?1658375306

- id: doi:10.1016/j.fuel.2022.123615
  image: https://ars.els-cdn.com/content/image/1-s2.0-S001623612200480X-gr4.jpg

- id: doi:10.1016/j.jcou.2021.101728 
  image: https://ars.els-cdn.com/content/image/1-s2.0-S221298202100295X-gr1_lrg.jpg