blank_issues_enabled: true
contact_links:
  - name: 💬 Start a discussion
    url: https://github.com/TSdreamer
    about: I need help, I have a question, or other discussion.
  - name: 📚 Docs issue
    url: https://github.com/TSdreamer
    about: I have a question or issue related to the template documentation.
